// ============================================================
// DIAGNOSES.JS — the searchable list of diagnoses shown in the
// autocomplete box. Add anything you like here; it's fine to
// include far more than your puzzle answers so guessing isn't
// trivially narrowed down. Every puzzle's "answer" and "accepted"
// values should ideally also appear somewhere in this list.
// ============================================================

const DIAGNOSIS_BANK = [
  "Acute otitis media (AOM)",
  "Otitis externa",
  "Acute bacterial sinusitis",
  "Streptococcal pharyngitis",
  "Viral pharyngitis",
  "Croup",
  "Bronchiolitis",
  "Respiratory syncytial virus (RSV) infection",
  "Influenza",
  "COVID-19",
  "Community-acquired pneumonia",
  "Mycoplasma pneumonia",
  "Asthma",
  "Allergic rhinitis",
  "Anaphylaxis",
  "Atopic dermatitis (AD)",
  "Eczema",
  "Psoriasis",
  "Eczema herpeticum",
  "Contact dermatitis",
  "Urticaria",
  "Hand, foot, and mouth disease",
  "Herpangina",
  "Roseola infantum", "Exanthem subitum", "HHV-6 infection", "Sixth disease",
  "Fifth disease",
  "Scarlet fever",
  "Varicella",
  "Measles",
  "Mumps",
  "Rubella",
  "Pertussis",
  "Infectious mononucleosis",
  "Viral gastroenteritis",
  "Constipation",
  "Functional abdominal pain",
  "Intussusception",
  "Pyloric stenosis",
  "Gastroesophageal reflux",
  "Appendicitis",
  "Celiac disease",
  "Inflammatory bowel disease (IBD)",
  "Urinary tract infection (UTI)",
  "Pyelonephritis",
  "Vesicoureteral reflux (VUS)",
  "Nephrotic syndrome",
  "Poststreptococcal glomerulonephritis (PSGN)",
  "Henoch-Schonlein purpura (HSP)",
  "Hemolytic uremic syndrome (HUS)",
  "Kawasaki disease",
  "Juvenile idiopathic arthritis (JIA)",
  "Systemic lupus erythematosus (SLE)",
  "Iron deficiency anemia (IDA)",
  "Sickle cell disease (SCD)",
  "Aplastic anemia",
  "Immune thrombocytopenic purpura",
  "Leukemia",
  "Type 1 diabetes mellitus",
  "Diabetic ketoacidosis",
  "Hypoglycemia",
  "Congenital hypothyroidism",
  "Hyperthyroidism",
  "Obesity",
  "Vitamin D deficiency",
  "Rickets",
  "Simple febrile seizure",
  "Complex febrile seizure", 
  "Juvenile myoclonic epilepsy (JME)",
  "Lennox-Gastaut syndrome (LGS)",
  "Absence seizures",
  "Epilepsy", 
  "Infantile spasm",
  "Meningitis",
  "Encephalitis",
  "Migraine without aura", 
  "Migraine with aura", 
  "Transient ischemic attack (TIA)",
  "Tension-type headache (TTH)", 
  "Trigeminal autonomic cephalalgias (TAC)",
  "Cluster headache",
  "Subarachnoid hemorrhage (SAH)",
  "Idiopathic intracranial hypertension (IIH)",
  "Pseudotumor cerebri",
  "Concussion", "Mild traumatic brain injury (TBI)",
  "Cerebral palsy",
  "Autism spectrum disorder (ASD)",
  "Global developmental delay (GDD)", 
  "Intellectual disability (ID)",
  "Hearing impairment",
  "Rett syndrome", 
  "Fetal alcohol spectrum disorder (FASD)", 
  "Attachment disorder", 
  "Selective mutism", 
  "Tic disorder", 
  "Tourette syndrome (TS)", 
  "Landau-Kleffner syndrome", 
  "Attention-deficit/hyperactivity disorder (ADHD)",
  "Speech delay",
  "Bacterial conjunctivitis",
  "Viral conjunctivitis",
  "Periorbital cellulitis",
  "Orbital cellulitis",
  "Cellulitis",
  "Impetigo",
  "Abscess",
  "Tinea corporis",
  "Tinea capitis",
  "Scabies",
  "Molluscum contagiosum",
  "Acne vulgaris",
  "Supracondylar humerus fracture",
  "Septic arthritis",
  "Osteomyelitis",
  "Slipped capital femoral epiphysis (SCFE)",
  "Legg-Calvé-Perthes disease (LCP)", "Idiopathic avascular necrosis of the hip",
  "Acute laryngotracheitis",
  "Epstein-barr virus (EBV) infection",
  "Minimal change disease (MCD)",
  "Membranoproliferative glomerulonephritis (MPGN)", 
  "Focal segmental glomerulosclerosis (FSGS)",
  "Transient synovitis", 
  "Malrotation", 
  "Ovarian torsion", 
  "Ectopic pregnancy", 
  "Pregnancy", 
  "Testicular torsion", 
  "Small bowel obstruction", 
  "Large bowel obstruction", 
  "Cholecystitis",
  "Pancreatitis"
];


