// ============================================================
// DIAGNOSES.JS — the searchable list of diagnoses shown in the
// autocomplete box. Add anything you like here; it's fine to
// include far more than your puzzle answers so guessing isn't
// trivially narrowed down. Every puzzle's "answer" and "accepted"
// values should ideally also appear somewhere in this list.
// ============================================================

const DIAGNOSIS_BANK = [
  "Acute otitis media",
  "Otitis externa",
  "Viral upper respiratory tract infection",
  "Acute bacterial sinusitis",
  "Streptococcal pharyngitis",
  "Viral pharyngitis",
  "Croup",
  "Bronchiolitis",
  "Respiratory syncytial virus infection",
  "Influenza",
  "COVID-19",
  "Community-acquired pneumonia",
  "Mycoplasma pneumonia",
  "Asthma",
  "Allergic rhinitis",
  "Anaphylaxis",
  "Atopic dermatitis",
  "Contact dermatitis",
  "Urticaria",
  "Hand, foot, and mouth disease",
  "Herpangina",
  "Roseola",
  "Fifth disease",
  "Scarlet fever",
  "Varicella",
  "Measles",
  "Mumps",
  "Rubella",
  "Pertussis",
  "Infectious mononucleosis",
  "Viral gastroenteritis",
  "Constipation",
  "Functional abdominal pain",
  "Intussusception",
  "Pyloric stenosis",
  "Gastroesophageal reflux",
  "Appendicitis",
  "Celiac disease",
  "Inflammatory bowel disease",
  "Lactose intolerance",
  "Urinary tract infection",
  "Pyelonephritis",
  "Vesicoureteral reflux",
  "Nephrotic syndrome",
  "Poststreptococcal glomerulonephritis",
  "Henoch-Schonlein purpura",
  "Hemolytic uremic syndrome",
  "Kawasaki disease",
  "Juvenile idiopathic arthritis",
  "Systemic lupus erythematosus",
  "Iron deficiency anemia",
  "Sickle cell disease",
  "Aplastic anemia",
  "Immune thrombocytopenic purpura",
  "Leukemia",
  "Type 1 diabetes mellitus",
  "Diabetic ketoacidosis",
  "Hypoglycemia",
  "Congenital hypothyroidism",
  "Hyperthyroidism",
  "Obesity",
  "Failure to thrive",
  "Vitamin D deficiency",
  "Rickets",
  "Febrile seizure",
  "Epilepsy",
  "Meningitis",
  "Encephalitis",
  "Migraine",
  "Mild Traumatic Brain Injury",
  "Cerebral palsy",
  "Autism spectrum disorder",
  "Attention-deficit/hyperactivity disorder",
  "Speech delay",
  "Bacterial conjunctivitis",
  "Viral conjunctivitis",
  "Periorbital cellulitis",
  "Orbital cellulitis",
  "Cellulitis",
  "Impetigo",
  "Abscess",
  "Tinea corporis",
  "Tinea capitis",
  "Scabies",
  "Molluscum contagiosum",
  "Acne vulgaris",
  "Supracondylar humerus fracture",
  "Septic arthritis",
  "Osteomyelitis",
  "Slipped capital femoral epiphysis",
  "Legg-Calve-Perthes disease"
];


